### ISSUE TITLE
minecraft does not start

### ISSUE THREAD

**Issue by M0xiito** [pedroksl/AdvancedAE#1]
I downloaded the add-ons that are needed for this mod, but minecraft does not start

**Comment by pedroksl** [comment]
Could you please post the crash report here so I could take a look?

**Comment by pedroksl** [comment]
I believe I have found the issue. AppliedFlux is actually a requirement to run the mod, the way it is coded in this version. I changed the requirements and published a new version. Please try the new version out with ApplieFlux installed and let me know if that fixes the issue.

**Comment by M0xiito** [comment]
Everything is working fine now. But I have a request, can you help me make the advanced molecular assembler faster?

**Comment by pedroksl** [comment]
I'm glad everything is working fine and hope you have a great time using this little mod.

As for the molecular assembler, there's no Advanced Molecular Assembler so I dont think I can help you there, but I can give you a few tips for now, just in case you haven't tried them yet.

- You can add acceleration cards to all your molecular assemblers, up to 4, and they are a massive speed up.
- You should always surround your pattern providers with as much molecular assemblers as you can. The most common setup is a tower containing 8 pattern providers and 8 assemblers with each provider touching 3-4 assemblers.
- Always have enough co-processor in your system to allow for the pattern provider to use all assemblers they have available. For normal setups, 3 should be enough. This number increases quite a bit when your start working with:
- There are Extended Molecular Assemblers, from ExtendedAE, which can craft 8 things at once, given you have enough co-processing units to handle all that in your crafting CPUs. If Your PP's are touching 4 Extended Molecular Assemblers, that means you need at least 4 * 8 = 32 co-processing units to use all available crafters. If you haven't installed it already, there is another mod called MEGA Cells that adds better co-processors with more threads that should help you get there using less space.

If you apply all of these, crafting should never feel slow, unless processing patterns are involved, which are the ones that send inputs to machines and then get something in return. They are usually the slowest crafting processes.
In case you didn't understand something I said, I'm going to leave a link here to a great tutorial by ChosenArchitect that goes through the autocrafting setup and visually shows the assembler tower I told you. He doesn't use ExtendedAE's components in the video, though. [You can find it here](https://youtu.be/ay0Js2TkI1E?si=Htd7Bc1B1oJV-xDZ)

I'm going to close this issue now and hopefylly you'll get your setup working. Thanks for pointing out the issue.
