### ISSUE TITLE
Bug with Advanced Pattern Provider and Mekanism I/O Configuration for Items during an Autocraft

### ISSUE THREAD

**Issue by yepbeeble** [pedroksl/AdvancedAE#10]
I had an Advanced Pattern Provider under an Ultimate Infusing Factory from Mekanism with it's face options not set to accept items from the bottom, where the pattern provider was. The recipe needed to put items in to the bottom, chemicals from the south side (front face) and output to the bottom. The chemical setting were correct, but the items were not set to input or output to the bottom face. 

I opened the Mekanism Items GUI to change this setting to allow it to craft while an autocrafting recipe was active, and it crashed the server when I switched from disabled -> input -> ouput (crashed initiated) ->Input/Output (goal, unachieved)

Attached is the crash log. Relaunching the world after the crash repeats the issue not allowing for reconnection to the world. 

I believe this is caused by the pattern provider attempting to put items in to a face of the machine that doesn't exist, because of how  Mekanism handles machine face interaction, when it's set to function, it completely disables the ability to interact with that side without that function present in the outside machines function. When it was set to none, it plain wasn't working. When I set it to input, it attempted to input the items into the Infusing Factory. When I cycled the options to switch Input/Output, I had to go through Output first. Since the Advanced Pattern Provider was accessing the INPUT function of that side of the machine, when I switched it to OUTPUT it can no longer input and crashes. 

[crash-2024-09-21_00.06.53-server.txt](https://github.com/user-attachments/files/17082806/crash-2024-09-21_00.06.53-server.txt)

**Comment by pedroksl** [comment]
Hi. I already checked for null faces when trying to push items, so this shouldn't have been a problem. When checking the log, its looks like you were very "lucky", because the check for null happened 3 line above the crash. Which shouldn't be possible since no tick happened in between. Either way, I added two extra checks for null faces that could help preventing this from happening again. I won't be able to generate a new release right now because I'm in the middle of finishing something else but I'll try to get it out as soon as I can. Thanks for the report.

**Comment by pedroksl** [comment]
Hey, just wanted to let you know that the potential fix for this issue is live and I would like to have feedback if it was actually fixed on your end. You can download the latest version from here or directly from curse forge.

**Comment by yepbeeble** [comment]
Yes, the issue has been fixed! I had a backup of the world before the broken state, and an instance of the bugged world. After updating to the latest version of the mod, the interaction that caused the crash no longer happens, and the world that was previously unloadable has been repaired.

**Comment by pedroksl** [comment]
Thank you for reporting back. Hope you enjoy the new block as well!
