### ISSUE TITLE
Feature request: ME Throughput Monitor

### ISSUE THREAD

**Issue by jpenilla** [pedroksl/AdvancedAE#12]
Similar to the storage monitor, but instead of simply displaying the current amount in the system, it displays the average throughput over X amount of time. For example, if you are storing MI steam in AE, you may want to know the net gain/loss of steam from your boilers and various users of steam. This way you know how much excess you are producing and can anticipate when you will need more boilers. Ideally, the sample length and display format could be configurable through a GUI, i.e. average over 5 seconds displayed in amount per tick, or average over 60 seconds displayed in amount per second.

**Comment by pedroksl** [comment]
I’m not gonna lie, I really really like this idea. I would have to see how feasible it is to implement and how much of a performance impact it would be. I definitely can’t keep track of all insertions/extractions from the network because that would be too much, but ticking once every 5/60 is probably doable without much of an impact. Thanks for the great idea, I’ll definitely see what I can do about it (after next block release which will happen before the weekend).

**Comment by jpenilla** [comment]
I'm not very experienced with AE's codebase (I've made a couple of small PRs but nothing major), so I didn't get very far. But I had an attempt at this and it seems like IStorageWatcherNode could be used in a similar manner to the storage monitor, and then the tick handler could be very lightweight, just storing the current value into an array. This way we wouldn't need to query the network very often (probably just on grid initialization). Even if it ran every tick I don't think the performance impact would be very different from a storage monitor with this approach, but you are right that every tick is probably not needed anyway. Sorry if this is naive and I'm missing something important, but thought I would drop this comment anyway.

**Comment by pedroksl** [comment]
Looking at IStorageWatcher, it seems like it would be the perfect solution if you wanted to monitor a few stacks. Something like a monitor where you have to manually register the stacks you want to get tracked. It will be notified of every change that happens to the stored amount of said item. Meaning it would receive a lot of signals if you registered the entire network, and the processing would be very performance consuming. The other option is to try an query every item on a specified interval and then comparing with a cache of the previous query. This would take a lot of processing in a single tick but the interval can be changed and doesn't impact performance at all. A tradeoff has to be made here. If I were to monitor a given amount of stacks registered through drag/drop the tracking could be done nearly real-time. On the other hand, monitoring the entire network would probably be done making big queries one in a while. (The performance hit could probably be minimized by moving the processing of the data to a different tick or a thread, something to think about).

**Comment by jpenilla** [comment]
> Looking at IStorageWatcher, it seems like it would be the perfect solution if you wanted to monitor a few stacks. Something like a monitor where you have to manually register the stacks you want to get tracked.

This is what I had in mind originally (one stack per monitor, same as base AE storage monitor), so I think this 'tradeoff' would be fine.

If someone placed multiple throughput monitors for a single stack this would result in duplicate work though, so maybe it makes sense to have some sort of grid-wide manager/cache that backs the monitors? But it's probably best to keep it simple and avoid premature optimization for the initial implementation.

Monitoring the whole network for some sort of "Throughput Terminal" is an interesting idea, but probably overkill since players are only likely to care about the throughput of a couple specific stacks.

**Comment by pedroksl** [comment]
This boils down to two options, then:

1) A Throughput terminal, that doesn't render anything on the block itself but has the ability to track, let's say, 9 stacks at once.
2) A Full block monitor (design can be changed to make it lean like a terminal if needed) that tracks a single stack, but renders what's being tracked without any need to interact with/open GUI after setting what to be tracked.

The second option seems limiting to me, although it would allow for some cool room designs with all tracked stacks in the walls. However the first is far more useful and could be implemented in a wireless terminal further down the road if reception for it is great.

**Comment by jpenilla** [comment]
I'd be very happy with either of those options!

**Comment by pedroksl** [comment]
I'm happy to report that the throughput monitor has been implemented and will be part of the next release of my mod. Here is a sneak peek:
![image](https://github.com/user-attachments/assets/cb8deae5-9d64-4f1c-b694-e3c672945c16)

**Comment by pedroksl** [comment]
Closing this thread as the request has been implemented and released. Thank you for the suggestion and I hope you enjoy using it. Feel free to report any issues you have with the implementation.

**Comment by jpenilla** [comment]
Awesome, thanks again! I can't wait to try it out.
