### ISSUE TITLE
Can't understand how advanced pattern works

### ISSUE THREAD

**Issue by PingouinDuTurfu** [pedroksl/AdvancedAE#13]
Hello,

I am having an issue with the use of the Advanced pattern. I am unable to get the items to come out on the specific faces of the Advanced extended pattern provider.

What I did:

- Created a pattern with the craft (logical processor).
- Modified the pattern with the Advanced pattern encoder by specifying the faces.
- Placed the Advanced pattern in an Advanced extended pattern provider.

However, the Advanced extended pattern provider doesn't seem to use the registered faces and behaves in a classic round-robin manner. Am I missing something, or am I doing something wrong?

I can't find any usage examples, so I took the liberty of contacting you.

Have a great day!

![pattern](https://github.com/user-attachments/assets/0297d800-46a6-4331-98b2-11269c8eec04)
![provider](https://github.com/user-attachments/assets/719c54df-985f-4aea-bd60-4f6d126fb413)
![output](https://github.com/user-attachments/assets/a56614df-e899-4b58-a9d7-0dbaa21b7012)

**Comment by pedroksl** [comment]
Hello,

I think you only missed the reference point of the advanced patterns. They let you specify the faces of the target machine that will be used for item insertion. This means that it will try to push, in your case, redstone on the top side of every adjacent machine that allows for it, and the others on the down face. In the case of extended inscribes, with the automation mode on, they accept all items from all sides, so the advanced pattern won’t make a difference there. It probably would if you were to turn on the sided inputs on them (it’s a config on the left side). With sided inputs they want redefine from on of the sides and top slot comes from the top, bottom slot comes from the bottom. But either way the top and bottom inscribed will receive the same items if they are configured the same way. If you want to do different things with each of them you will need a separate pattern provider. (Or just use a circuit slicer/crystal assembler combo from ExtendedAE which works great and very fast)

**Comment by PingouinDuTurfu** [comment]
Thank you very much for this quick and precise response!
