### ISSUE TITLE
[Feature-Request] Throughput monitor reduced update time?

### ISSUE THREAD

**Issue by ImMorphi** [pedroksl/AdvancedAE#19]
Hi, really loving the mod so far in my play through on atm10, however I've noticed with a electric quarry from Modern Industrialization (Max over clock no upgrades) creating ores getting put into ae2 drive, the throughput monitors will stay at 0/s or may briefly show +1/s every now and then. Is it possible to slow down the update time to multiple seconds or possibly allow configuration of update time (in game or config) for the throughput monitors?

I'm not gonna pretend I know if this is a simple change or not, just a thought :D

Attached photo for reference:
![image](https://github.com/user-attachments/assets/886eb8ab-e00a-41bc-8b7b-dcbcef65c195)

**Comment by pedroksl** [comment]
Interesting that you’re the first one to actually ask for a slower monitor, generally people ask for a /t monitor. I’ve already implemented a mechanic to allow for this, it’s gonna be released in the next update which should hopefully happen this weekend.

**Comment by pedroksl** [comment]
Hi. Just wanted to let you know this feature has been implemented and is in the latest release. To change the configuration you'll need a Throughput Monitor Configurator. Simply right-click the monitor while holding it and it will cycle between modes!
