### ISSUE TITLE
[1.21.1] Client Crash when hovering over invalid pattern

### ISSUE THREAD

**Issue by micrwvae** [pedroksl/AdvancedAE#2]
### Describe the bug

hovering over an invalid pattern crashes me instead of giving me the option to take it out to clear it

### How to reproduce the bug

updated the allthemods 10 modpack and was rearranging my patterns
hovering over a invalid one crashed the client

previously i was able to view them just fine

### Expected behavior

pattern displays as invalid and can be cleared manually 

### Additional details

crash happening on
the allthemods10 modpack: 0.41
ae2 19.0.22

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

https://mclo.gs/tGcakA0

**Comment by pedroksl** [comment]
I have updated the release yesterday with an attempted fix for this issue. Did you update to the 0.3.1 version and tried again?
If that didn't fix the issue, I'll have to look more into it. If it didn't fix it, I would like a little bit more information.

1) From the logs it seems the crash happened when hovering a crafting pattern. Is this correct or was it an advanced processing pattern?
2) How did you generate the invalid pattern?

**Comment by pedroksl** [comment]
Hey, nevermind all that.
I found the issue and released a new version with a fix for it.
Please update as soon as possible and report the results.
Thanks.

**Comment by micrwvae** [comment]
havent had a chance to update sorry
but thanks on the quick fix
