### ISSUE TITLE
Latest version depends on some mods without listing them as a dependency

### ISSUE THREAD

**Issue by Pumpkin7266** [pedroksl/AdvancedAE#21]
![image](https://github.com/user-attachments/assets/5ac40058-32c8-4ebd-9de3-1c9dbc3fdf47)

**Comment by Pumpkin7266** [comment]
![image](https://github.com/user-attachments/assets/464776a1-5ad8-4f80-9e45-d595f8c835d1)
Also Applied Flux

**Comment by Hexblood** [comment]
Ran into the Mek one as well. I hope this is not intended.

**Comment by pedroksl** [comment]
Hi. This was not intentional, and has already been fixed in dev. I'll push a hotfix very soon.

**Comment by pedroksl** [comment]
The hotfix has been released!
