### ISSUE TITLE
Quantum infusion in Reaction Chamber can not interact correctly with bucket

### ISSUE THREAD

**Issue by YuezhangWang** [pedroksl/AdvancedAE#24]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

1.0.6

### Modloader version

Neoforge: 21.1.72

### Issue description

1. Source bucket doesn't become to empty bucket
    1. Get a Quantum infusion bucket and right click on the left side.
    2. Chemical from "Empty 0/16B" to "1B", but the Quantum infusion bucket is still full in inventory.
    3. There is the same problem using water bucket as the input when produce Quantum infusion. The source bucket never becomes empty.
2. Destination bucket can't get the chemical produced out
    1. Produce 1B Quantum infusion (5B water + 1 dust).
    2. Left click on the right side. The bucket is still empty, either the chemical disappeared. 

I tested in Survival mode. In addition, I found that [Large Fluid Tank](https://modrinth.com/mod/large-fluid-tank)'s tank and [Mekanism](https://modrinth.com/mod/mekanism)'s gauge dropper and fluid tank work correctly. They can handle left click and right click on the both sides.

**Comment by pedroksl** [comment]
Hey, thanks a lot for the bug report. I fixed it in the latest release of the mod.
