### ISSUE TITLE
Almost All Items Inaccessible In Survival Due To Recipe Missing

### ISSUE THREAD

**Issue by MrLittleFox0220** [pedroksl/AdvancedAE#27]
The "quantum infusion" fluid is missing a crafting recipe or isn't covered in the guide on how to find/get. That means that all of the items that requires quantum alloy are inaccessible in survival mode. I hope that gets fixed soon.

**Comment by pedroksl** [comment]
Hey, I’m just gonna paste here the answer I gave to you over at curseforge:

 The recipe is not missing. JEI does not have it. I only support REI/EMI. Packs that use the FTB JEI extras addon to add unofficial support to JEI will have to either manually add EMI or wait until they update. But to fix your issue right now, the recipe for quantum infusion is 5B of water and 1 Quantum Infused dust to make 1B of Quantum Infusion.

**Comment by MrLittleFox0220** [comment]
Oh. I've never heard of a mod that doesn't work with JEI until now. Thanks for telling me! :)

**Comment by pedroksl** [comment]
I’m just following my base mod. As of 1.21.1, Applied Energistics no longer supports JEI. You only see recipes in there because the JEI mod creator himself made a mod to add compatibility back. We’re trying to move on to EMI, which is the better alternative.

**Comment by Tenchu98** [comment]
emi sucks and should never be supported, it kills server performance.

**Comment by pedroksl** [comment]
- Give me a spark report or at least *something* to back your claims and I’ll consider it
- The decision to drop JEI was not mine, but ae2 itself
- Their decision was made for a very good reason, the JEI devs did something they shouldn’t to them (I won’t say more, you can ask them if you want)
- It takes about 4 times more code to do the same thing in JEI vs EMI.

Your baseless claim is invalid.

**Comment by Tenchu98** [comment]
I could go dig through our spark reports from when we hosted tnp7, but that would be a waste of my time. EMI is a huge tps mess and caused the server to lag and crash quite often thanks to it's constant syncing. You can try to dismiss the reality with the statement that it is baseless, but you could also look online and see where a lot of people experienced the exact same thing.
