### ISSUE TITLE
[Feature-Request] Support of Magic mods (Like ars nouveau)

### ISSUE THREAD

**Issue by NewLordZeeCaptain** [pedroksl/AdvancedAE#30]
Hi, I think it would be great if this mod had some synergy with magic mods. For example, increase total amount of Mana (Like Mana boost enchant) & boost Mana Regen using ars nouveau Source "energy" stored inside Source cells from Ars Energistique mod
P.S: After last update I fell in love in this armor. Thanks for buffing it!

**Comment by pedroksl** [comment]
Hey, thanks for the suggestion, however I'm not sure it is doable as of right now.

To add integration with stuff like that I would need to add Ars Energistique as a dependency, which I don't want to do, as that would make me also dependent on ars, and that would make me dependent on JEI, which I don't even support. Generaly dependencies should be kept to a minimum.

There are ways to make conditional dependencies, and I can think of something to add in the future, but it is not planned for right now.

Additionally, the armor (which is probably where you wanted the source/mana synergy) is stealth themed and adding mana to it makes no sense. More upgrades will be added to it to enforce the theme, which is admitedly lacking right now, and mana options would break that. Hopefully you'll understand this.
