### ISSUE TITLE
Eternal Steak being permanently eaten when using Quantum Auto Feed Module 

### ISSUE THREAD

**Issue by 7Kav** [pedroksl/AdvancedAE#31]
Title for the most part
Video Link shows the issue (I can give the actual file if needed just needs to be compressed) 

https://streamable.com/1fkv2b

**Comment by pedroksl** [comment]
Interesting issue. To consume the food I use the actual eat function present in any food item, and that action returns any remainders, if there are any, which I push back to ae2. I can think of a few possible issues, there, but I will need to test them. Was this on a single player world or a server?

**Comment by 7Kav** [comment]
This was tested on my server but I can also test on a single player if needed

**Comment by pedroksl** [comment]
Testing this right now and it's exactly as expected.

![image](https://github.com/user-attachments/assets/0f85579e-832e-4d83-8599-3b1781dfe9af)

So when I call "eat" it return the optional (which is this case is null), so it becomes air.
Does this item work in another auto feed mod? Like sophisticated backpacks?

**Comment by pedroksl** [comment]
I found a way to make it work that doesn't break normal food items.
The fix will be in the next release.
