### ISSUE TITLE
[Feature-Request] Quantum Requester

### ISSUE THREAD

**Issue by Cottagex** [pedroksl/AdvancedAE#37]
A quantum requester that has more slots than the current 5 on the ME requester. Maybe with a threshold or stock feature kinda like the quantum crafter.

**Comment by pedroksl** [comment]
Hey, I appreciate the suggestion but I don't want to overstep my boundaries, in general. Creating an expanded version of the requester would be one example. The only viable option would be to make it a dependency for my mod, which is something I don't want to do. I can suggest you just make more requesters, like 16 of them, and you will be set for everything you might need.
