### ISSUE TITLE
Missing Status display

### ISSUE THREAD

**Issue by cameron581** [pedroksl/AdvancedAE#4]
I have built the quantum compute core; however, I cannot right click it like AE2 crafting to get the GUI to pop up. Am I missing something? Playing on the latest of ATM 10

**Comment by cameron581** [comment]
![image](https://github.com/user-attachments/assets/f9f00df0-deb9-4d6e-8311-147f0dad03bc)

**Comment by pedroksl** [comment]
Hey. The GUI for both the core or the quantum computer isn’t implemented yet. You can access it via AE2 crafting terminal and clicking on the hammer icon on the top right. The interface will be implemented soon, don’t worry about that.

**Comment by pedroksl** [comment]
This was implemented in the latest release, although in a beta state. Further bug reports are appreciated!
