### ISSUE TITLE
Quantum Infusion voiding itself when enters the AE2 System

### ISSUE THREAD

**Issue by fairdev2003** [pedroksl/AdvancedAE#41]
Whatever you do, exporting, manual input this fluid, is always void Quantum Infusion in the system so it cant be automated with pattern providers. Also in the JEI it seems that Quantum Infusion is not interpreted as fluid but something else

https://github.com/user-attachments/assets/67d80d93-ede5-4041-b7fd-fc4383054500

**Comment by fairdev2003** [comment]
UPDATE: Other fluid storage options are just fine when you auto output Quantum Infusion so it can go through the system

![image](https://github.com/user-attachments/assets/2be57501-3868-4c63-88a1-7aa8dd0413b9)

**Comment by pedroksl** [comment]
Hey. Without looking at your system it’s hard for me to debug what’s going on. I assume you’re playing FTB evolution, right? That pack uses JEI which I didn’t make the integration for. It was FTB themselves and I know there’s a bug currently where no fluid outputs are displayed. I don’t know if that played a role in your encoding, potentially breaking the pattern, but it’s possible. Quantum infusion is definitely a fluid and it works fine in other packs. Might I suggest adding EMI even if just for a test? EMI works on top of jei, so you don’t need to remove anything. If that doesn’t work, I can try and help you solve that issue through here.

**Comment by pedroksl** [comment]
Wow, that's interesting. I didn't know sinks could do that. Did you connect it with a non-partitioned storage bus?

**Comment by fairdev2003** [comment]
I did. When storage is connected to sink and isn't partitioned, ae2 will push automatically any liquid coming to the network into sinks. To fix that, you need to set prior storage bus lower than your main storage and its should be ok but also you can add additional seecurity - partition, extract only on the storage bus etc. Sorry for a problem bro, Have a great day/night :)

**Comment by pedroksl** [comment]
Be careful with setting it at a lower priority though, because that can lead to your system inserting water into a fluid cell you didn’t want to. I’d rather make it a higher priority, but partitioned. Good luck and have fun!
