### ISSUE TITLE
[Very Minor Issue] Pick Crafter Card has the same description as Portable cell workbench

### ISSUE THREAD

**Issue by 7Kav** [pedroksl/AdvancedAE#42]
Im not sure if this is intentional or not but I thought that it was better to say something than to not

![image](https://github.com/user-attachments/assets/f86a5fbe-ab73-4f29-b515-e08dcf82c0d5)
![image](https://github.com/user-attachments/assets/bbc31114-9df8-40ea-9984-95b9549fe654)

**Comment by pedroksl** [comment]
Yeah, it’s not intentional, I’ve seen this before and I’m waiting for the next release to fix it. New release should happen today. Thanks for the reminder about it.
