### ISSUE TITLE
[1.20.1] quantum computer doesn't work on a clean slate

### ISSUE THREAD

**Issue by hyperclocked333** [pedroksl/AdvancedAE#43]
ae2 version: 15.2.13
advancedAE version: 0.3.1 - 0.3.3

"This leads me to assume it's some interaction with other mods in the modpack. I tried running the same mods as ATM9 but ran into some compatibility issues, and couldn't load it in debug mode. Trying to solve without debug tools would be like trying to write code in the dark. I'll try to think of some way to fix this, but for now there's not much I can do."

https://github.com/pedroksl/AdvancedAE/issues/3#issuecomment-2323179084_
         
to test this, i created a new test pack to see if this was so, and if it was just other mods (i have a custom modpack for friends this was not working on)

![image](https://user-images.githubusercontent.com/107872377/387061908-efb7023c-1204-409e-8b0b-28621346176b.png)

the pack uses the bare minimum mods needed to run AdvancedAE.

![image](https://user-images.githubusercontent.com/107872377/387062690-6d568587-a569-43f0-9449-7f0fc9b4b487.png)

upon testing, the computer does not let me cancel at all. i have tested this on all three versions of the mod's backport from 0.3.1 - 0.3.3. if theres any important replication/debug steps that could help, do let me know

also i dont expect this to be resolved swiftly and stuff i know 1.20.1 is a rushed backport, but i just wanted to clarify that it was happening on clean packs too

**Comment by hyperclocked333** [comment]
that sucks, but yeah i see the hassle
thanks for the good response btw

**Comment by hyperclocked333** [comment]
wait, do you know where the crafting jobs are handled file-wise in ae2? tried looking through the data files in the world and i didnt find anything.

would like to cancel some hung recipes in my quantum computer manually

**Comment by pedroksl** [comment]
The jobs are saved in the NBT data of the TileEntity. There are no external files involved. And in the case of the quantum computer, it has a dynamic array of internal cpus, each with their own nbt data saving their own jobs.

**Comment by hyperclocked333** [comment]
ok. thank you so much (again)!
