### ISSUE TITLE
[1.20.1] Recipe change suggestion

### ISSUE THREAD

**Issue by criscky** [pedroksl/AdvancedAE#44]
change the Quantum Entangled Singularity for simple Quantum Singularity in the recipes, because when you craft the Quantum Entangled Singularity it gets assign an id, making it impossible to autocraft

unless your vision for the mod is making the items impossible to autocraft with ae2, if there's a workaround i'll take that, but i cannot see that being the case, because of how the Entangled one works

**Comment by pedroksl** [comment]
Hey, I'm here to say I finished the backporting of most of the 1.21.1 stuff. This should include fixes to the existing stuff and a ton of new things to play with. The recipe issue is also fixed in this version, and a lot of them are changed. Hope you have fun.
