### ISSUE TITLE
stuff is missing and quantum computer dosent work

### ISSUE THREAD

**Issue by rat123fuckthissititwasa** [pedroksl/AdvancedAE#46]
it dosent even connect to the me system by cable or controler tuching it

**Comment by pedroksl** [comment]
What version of Minecraft are you on? Is this 1.21?

not connecting to a cable means it’s not formed. If it was before, there’s an issue with it and I would try breaking it and forming again. But I’ve fixed this in 1.21, so I’m assuming you’re using the old version of the mod.

**Comment by rat123fuckthissititwasa** [comment]
It's 1.20.1 forge idk how it works because guide is broken

**Comment by pedroksl** [comment]
That is to be expected, then. The quantum computer was a rushed backport when I did it. All of the fixes for the newest version were not ported to the previous version.

I'm right now making a full port of the new version, but this is taking some time. I will report back when I'm done with it.

**Comment by rat123fuckthissititwasa** [comment]
To 1.20.1 right?

**Comment by pedroksl** [comment]
Yes, exactly. I’ve done most of it, just need a ton of testing, right now.

**Comment by pedroksl** [comment]
Hey, I'm here to say I finished the backporting of most of the 1.21.1 stuff. This should include fixes to the existing stuff and a ton of new things to play with. Hope it fixes your issue. Thanks for the patience.
