### ISSUE TITLE
Quantum Armor not present in 1.20.1

### ISSUE THREAD

**Issue by Fred-Redstone-2** [pedroksl/AdvancedAE#47]
Hello,
I have noticed that the Quantum Armor is not present in the 1.20.1 version of the mod. Why is that? Is it planned to be added soon? I really want to test that.

Thanks!

**Comment by pedroksl** [comment]
Hey. I just released the quantum armor in the latest version. Should be available in curseforge by the time you see this.

**Comment by Fred-Redstone-2** [comment]
Wow! You're so efficient!
Thank you very much for making that a priority! I'll make sure to try it

**Comment by pedroksl** [comment]
Hey, sorry about that but I had to remove that version, as well as the subsequent fixes for it because there were too many bugs being reported and I wasn’t able to fix those today. I will re release the armor possibly tomorrow after I get a more stable version.
