### ISSUE TITLE
Crash when opening I/O settings in Reaction Chamber

### ISSUE THREAD

**Issue by zako890016** [pedroksl/AdvancedAE#48]

**Comment by zako890016** [comment]
I also tried it with AdvancedAE and its prerequisite mods only, but it crashed.

**Comment by pedroksl** [comment]
Hey. Can you please tell me what version are you running? I assume it’s 1.20. Also, do you have a crash log to give me?

**Comment by zako890016** [comment]
crash log
https://gist.github.com/zako890016/f88881897ede131c91e9cbda0a02599a
latest log
https://gist.github.com/zako890016/6bf9e1e4afb3c946f0a1b4863fe6befc

**Comment by pedroksl** [comment]
That's a very unexpected issue, because it's complaining about something that would case the software to not even compile.
Additionally, that function is provided by the super class of the reaction chamber, which is implemented by Applied Energistics 2 itself and not my mod.
And to make matters worse, it works fine in my dev environment.
I'll look into it and see if I can figure it out. I will report back on this.

**Comment by pedroksl** [comment]
I found a solution for this issue, I will be releasing it with a bunch of other stuff very soon.

**Comment by zako890016** [comment]
I see you have a solution... thank you.わ

**Comment by pedroksl** [comment]
The other features I was trying to push are taking longer than expected so I just released a hotfix for this issue. It's up now in curseforge/modrinth. Thanks for the report.

**Comment by zako890016** [comment]
I updated and checked it and it crashed again, so I'll put a log
crash log
https://gist.github.com/zako890016/4f8e7e38d523ec455c9527cbe6bf78da
latest log
https://gist.github.com/zako890016/4a74b66b3bc7a71e271a876e4f236712

**Comment by pedroksl** [comment]
Same issue, different method. I’ll fix it as soon as possible.

**Comment by pedroksl** [comment]
Just finished uploading to curseforge.
Just wait until it's processed. Hopefully this is the last time we see this issue happening. Thanks again for the report.

**Comment by zako890016** [comment]
It's fixed, thanks for the update twice!
