### ISSUE TITLE
Suggestion: Quantum Computer - Allow to be Player Crafts Only

### ISSUE THREAD

**Issue by Ardrial** [pedroksl/AdvancedAE#6]
Would be nice to be able to dedicate a quantum computer to be Player Crafts only instead of default all crafts.

**Comment by pedroksl** [comment]
Sorry for taking so long to reply to this.
I'm here to tell you that this feature is now implemented in dev and should be out in the next release.
You will be able to use the quantum computer's ui in the same way you would a normal cpu, using the left toolbar menu to select between all/player/automation crafts only.
