### ISSUE TITLE
[Bug] Quantum Crafter Keep parameter doesn't save

### ISSUE THREAD

**Issue by DomiIRL** [pedroksl/AdvancedAE#60]
Every time I set a number of items to keep from the ingredients the amount just resets to 0 after closing the terminal.
Limit parameter on the output works just fine.

Reproduction:
1. Open Quantum Crafter
2. Select settings of pattern
3. Set "Keep" parameter
4. Confirm with Enter
5. Close Terminal
6. Reopen and check number is 0 again

Version: 1.0.6
Other Mods: ATM9TTS Modpack
Errors in Log: None

![javaw_cYRWpB0eUh](https://github.com/user-attachments/assets/b99a5efd-e5f4-4601-84c5-7e05c61797b8)

**Comment by pedroksl** [comment]
This issue has been fixed and will be in the next release.
