### ISSUE TITLE
Strength card fixes a cap on the damage dealt

### ISSUE THREAD

**Issue by Fred-Redstone-2** [pedroksl/AdvancedAE#61]
Mod version: 1.0.4-1.20.1
Forge version: 47.3.12

Hello,

I was testing the Quantum Suit in 1.20.1 and I noticed that when I equip the strength card on the chestplate, the Chaotic Staff of Power from Draconic Evolution that I configured to do 1000 ATK DMG only does 15 (to a Wither). When I removed the strength card from the chestplate, it fixed it. I suspect that the strength card is actually fixing the additional damage at 10 instead of adding it to whatever other damage boost the player has.
Is is possible to fix this issue?

Thanks!

**Comment by pedroksl** [comment]
Hey, I made an attempt at fixing this issue. It's mostly likely linked to attribute IDs in Forge. I've created my own attributes with unique IDs, instead of reusing forge's. That should resolve the issue. It will be present in the next release.

**Comment by Fred-Redstone-2** [comment]
I tested it and it's fixed! It does indeed add 10 Attack Damage to every hit.
