### ISSUE TITLE
[BUG] - ATM9TTS: when choosing directional output for reaction chamber.

### ISSUE THREAD

**Issue by ccarney96** [pedroksl/AdvancedAE#62]
When clicking the GUI button `directional output` on the reaction chamber, minecraft just closes, will provided the logs.#

Also not entirely sure the reaction chamber works at all when connected to a pattern provider? can't seem to get it working without manually putting the items into it.

```The game crashed whilst rendering screen
Error: java.lang.AbstractMethodError: Receiver class net.pedroksl.advanced_ae.common.entities.ReactionChamberEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.core.BlockPos getBlockPos()' of interface net.pedroksl.advanced_ae.api.IDirectionalOutputHost```

**Comment by pedroksl** [comment]
Hey, both of these issues have already been addressed, you just need to manually update the mod and they will be fixed.
