### ISSUE TITLE
Advanced Pattern Provider Upgrade crashes without ExtendedAE

### ISSUE THREAD

**Issue by MuteTiefling** [pedroksl/AdvancedAE#67]
https://mclo.gs/7BURCmo

Crash happens when applying this upgrade to a standard AE pattern provider. If this is meant only as a compatibility item for Extended AE it should probably be hidden/disabled when that mod isn't present.

**Comment by pedroksl** [comment]
That’s not intentional, that’s a mistake on my part. It’s something I forgot to change when removing ExtendedAE dependency. It’s an easy fix that I will implement for the next release.

**Comment by pedroksl** [comment]
This issue has been fixed and will be in the next release. Thanks for the report.

**Comment by MuteTiefling** [comment]
Thanks!
