### ISSUE TITLE
[Bug] Creative flight remains after quantum chestplate is removed

### ISSUE THREAD

**Issue by Attelisya** [pedroksl/AdvancedAE#71]
The point is that if you make a flight card for a quantum chestplate, you get creative flight. But after removing the armour, creative flight remains, but slower than with the chestplate. I'm not sure if that's the way it should be :)
P.S. im playing on ATM9 pack with adding this mod version 1.0.6

**Comment by Fred-Redstone-2** [comment]
Can confirm: I have this issue as well on my server

**Comment by pedroksl** [comment]
This issue has been fixed and will be in the next release. Thanks for the report.
