### ISSUE TITLE
cannot launch world since update to DW20 1.21 modpack version 1.8.0 - Advanced AE ticking world

### ISSUE THREAD

**Issue by jlp1528** [pedroksl/AdvancedAE#72]
logs:
https://pste.ch/ipoyokuqaz.rb
https://pste.ch/eyojuniqun.coffeescript

I updated to pack version 1.8.0 and now crash with these errors on trying to load my world.

Is there somewhere I could upload my world for testing???

**Comment by jlp1528** [comment]
I disabled AdvancedAE to get the world to load, but instantly crashed when I placed an advanced pattern provider.

**Comment by pedroksl** [comment]
Looking at AE2 code I found out the issue. They changed the name of an enum entry and broke my code in doing so. I will need to release a new version to be compatible with the latest ae2. For now you could downgrade your ae2 version if want to use both. You shouldn't lose too much in doing so. (But please make a backup before that).

I will try to release a new version either today or tomorrow, to fix that.

**Comment by jlp1528** [comment]
Mentioned on wrong bug report. I find too many bugs...

**Comment by pedroksl** [comment]
I fixed the compatibility issue. I will make a new release in the next few minutes containing it. Thanks for the report.
