### ISSUE TITLE
Server crash IMPORTANT

### ISSUE THREAD

**Issue by Reaviik** [pedroksl/AdvancedAE#75]
https://mclo.gs/WTR97co

**Comment by Reaviik** [comment]
Versão 1.0.7-1.20.1 forge 47.2.20

**Comment by pedroksl** [comment]
This is the exact issue that 1.0.7 version fixes. It was due to an ae2 update that broke things. Are you 100% sure that’s the version you are using?

**Comment by Reaviik** [comment]
Sorry for the confusion in the numbers, and even when I updated 1.0.6 it was still not available this morning, thanks for the correction and sorry for the confusion ^^

**Comment by Reaviik** [comment]
hmmm, updated everything on CurseForge today at 10:00 +-

But anyway, I'm going to test the new version here, <3
