### ISSUE TITLE
[BUG] Equipping the Step Assist Card on the Quantum Armor makes the game crash

### ISSUE THREAD

**Issue by Fred-Redstone-2** [pedroksl/AdvancedAE#79]
Forge version: 47.3.12
Mod version: 1.0.7-1.20.1

The issue is pretty much as said in the title. When I equipped the Step Assist Card on my quantum armor, my game instantly crashed. I joined the crash report to this issue.,

Please fix this as soon as possible!
[crash-2024-12-14_20.55.49-server.txt](https://github.com/user-attachments/files/18138576/crash-2024-12-14_20.55.49-server.txt)

**Comment by pedroksl** [comment]
I don't know what to tell you. Your server says it doesn't know a forge attribute. Did you have it working on a previous release? Because if so, the only thing I changed was I moved away from `ForgeMod.STEP_HEIGHT_ADDITION`, which is deprecated, to `ForgeMod.STEP_HEIGHT`, which is the correct one. And even in forge implementation, they are both equal. That means reverting probably still wouldn't fix the issue for you.

**Comment by Fred-Redstone-2** [comment]
It works on 1.0.6 no problem.But in 1.0.7, as soon as I put the card in, my game crashes.
Also, idk why it says server because I'm in singleplayer; I guess that the CurseForge Dashboard make the game think it's a server.

**Comment by pedroksl** [comment]
Even single player worlds run server and client. Server handles most of the stuff while client deals with what you see on the screen.

Another thing I've seen on your log:

```
// Hi. I'm Connector, and I'm a crashaholic
=========================
SINYTRA CONNECTOR IS PRESENT!
Please verify issues are not caused by Connector before reporting them to mod authors.
If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.
=========================
```

Is it possible that this has something to do with the crash? It is literally a forge attribute, so your game should have it, and it works fine in my dev environment. Maybe file an issue there and see if they have something to say about that? In the meantime you could keep using 1.0.6, if you didn't update to latest AE2.

**Comment by pedroksl** [comment]
Just as an information, this is the definition of the attribute I was using before:
![image](https://github.com/user-attachments/assets/34958b6a-344c-487e-a99d-adc09757302e)

All I did between releases was stop using the deprecated one and start using the recommended one.

**Comment by pedroksl** [comment]
Something just occurred to me. It could be that your forge version is older and doesn't have the new attribute. Or that could be neo's implementation and it really won't work with standard forge. Could you please try to update forge and let me know if that works? If it doesn't, I might have to revert that change to work with standard forge.

**Comment by pedroksl** [comment]
Hey, I just released a new version for the mod. Should be up in curseforge really soon. Hope that fixes your issue.

**Comment by Fred-Redstone-2** [comment]
It fixed it! Thank you so much!
