### ISSUE TITLE
Crashing in ATM 9: TTS when clicking "Directional Output" button in the Reaction Chamber

### ISSUE THREAD

**Issue by howradisit** [pedroksl/AdvancedAE#82]
Title says it all. Reaction Chamber makes my game crash when I click Directional Output in the UI

[crash-2024-12-22_09.41.09-client.txt](https://github.com/user-attachments/files/18222474/crash-2024-12-22_09.41.09-client.txt)

**Comment by pedroksl** [comment]
This has been fixed weeks ago but atm still haven’t updated the pack, yet, because of the ongoing revamp. Please make sure to always test the latest version of a mod before posting an issue.
