### ISSUE TITLE
Crash when clicking on the directional output on the Reaction Chamber

### ISSUE THREAD

**Issue by TheRedCyclops** [pedroksl/AdvancedAE#83]
I found this crash while playing ATM9, it can be consistently reproduced

**Comment by pedroksl** [comment]
Are you using the latest version of my mod?

**Comment by Wlnfr** [comment]
Just got the same problem on ATM9TTS. Updating AAE to 1.0.10(latest) and AE2 to 15.2.15(minimum required version for AAE) resolves it.

**Comment by pedroksl** [comment]
This is why I asked if he was on latest. This crash has been fixed weeks ago.
