### ISSUE TITLE
[Bug Report]: Progress bar and percentage are incorrect

### ISSUE THREAD

**Issue by andriihorpenko** [pedroksl/AdvancedAE#84]
### Minecraft Version

1.20.1

### Mod Version

1.0.10

### Did you test the latest version?

Yes

### Severity

Odd Results

### NeoForge Version

Forge 47.3.10

### Describe the Issue

For some reason, Quantum Computer GUI displays incorrect values for crafting percentage, causing incorrect progress bar values as well.

**NOTE**: Any terminal's crafting GUI looks fine. This issue is only and only in Quantum Computer GUI.
See "Additional Context" section for potential cause.

### Reproduction Steps

1. Fire up a chunky crafting recipe
2. Open the Quantum Computer GUI
3. Hover over an active recipe
4. Observe nonsensical percentage and progress bar

To compare with an expected result:
1. Fire up a chunky crafting recipe
2. Open any terminal and go to Crafting Status page
3. Hover over an active recipe
4. Observe correct percentage and progress bar

### Screenshots and Videos

<img width="1402" alt="image" src="https://github.com/user-attachments/assets/21d41490-c317-4e1e-92a7-aa9fc95c7ca9" />

### Additional Context

There were some commits regarding progress bar not that long time ago. This might be helpful.
https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/41f89e1ad913a2b1b75adf82bfe3708dfb968fd6

### Crash log

https://mclo.gs/dM6qEBj

**Comment by pedroksl** [comment]
I found the issue. It was a missing class from this pr: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/8266/commits

I added those changes and it should fix the issue.
