### ISSUE TITLE
[Bug Report]: Fill recipe button doesn't appear on EMI menu

### ISSUE THREAD

**Issue by TASC2** [pedroksl/AdvancedAE#85]
### Minecraft Version

1.20.1

### Mod Version

1.0.11

### Did you test the latest version?

Yes

### Severity

Odd Results

### NeoForge Version

forge 47.3.0

### Describe the Issue

The "Processing Patterns" of the "Reaction Chamber" cannot be auto-filled using EMI

### Reproduction Steps

This is a mod list
![3](https://github.com/user-attachments/assets/4efc2ac6-78bc-466a-994b-e33aa4b92b7e)

### Screenshots and Videos

![1](https://github.com/user-attachments/assets/da51460b-cc9d-49cd-b9eb-3079fec6b307)
![2](https://github.com/user-attachments/assets/3f71ab4c-c1c9-498c-9cc8-ee91bc766908)

### Crash log

None

**Comment by pedroksl** [comment]
Very interesting issue. AE2 doesn't have an EMI plugin in 1.20.1 and it works. Meanwhile, I *have* a ported EMI plugin, and mine doesn't work. Funnily enough, removing the plugin fixes this issue.

As AE2 itself doesn't support EMI by itself, I have no reason to, so removing the plugin should have no downsides. I'm releasing a new build containing the fix plus a few additions.
